name: Run Java Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run Maven Tests
        run: mvn test

      - name: Check Mail Secrets
        if: always()
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          if [ -z "$MAIL_USERNAME" ]; then
            echo "MAIL_USERNAME secret is missing"
            exit 1
          fi

          if [ -z "$MAIL_PASSWORD" ]; then
            echo "MAIL_PASSWORD secret is missing"
            exit 1
          fi

          echo "Mail secrets are available"

      - name: Send HTML Report Mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: Automation Test Report
          to: shaliniviswanathan42@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}

          html_body: file://target/surefire-reports/emailable-report.html